version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building JAR...
      - mvn spring-boot:build-image -DskipTests
      - echo Building Docker Image...
      - docker build -t potatomann/myapp:latest .
  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push potatomann/myapp:latest
      - echo Creating Dockerrun.aws.json...
      - |
        cat <<EOF > Dockerrun.aws.json
        {
          "AWSEBDockerrunVersion": 1,
          "Image": {
            "Name": "potatomann/myapp:latest",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": "8080"
            }
          ]
        }
        EOF
      - echo Zipping for deployment...
      - zip -r deploy.zip Dockerrun.aws.json

artifacts:
  files:
    - deploy.zip

env:
  secrets-manager:
    DOCKER_HUB_USERNAME: dockerhub-creds:username
    DOCKER_HUB_PASSWORD: dockerhub-creds:password
